name: test
dependencies:
  - bats
  - r-optparse
  - libpng
  - r-cairo
  - r-workflowscriptscommon >=0.0.8
  - r-seurat=4.0.0
  - r-uwot <0.1.11
  - r-loom
  - r-svglite
  - bioconductor-scater
  - r-seuratdisk
  - r-remotes
  - bioconductor-multtest
  - r-metap
  - pandoc