name: test
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - bats-core
  - r-optparse
  - libpng
  - r-cairo
  - r-workflowscriptscommon >=0.0.8
  - r-seurat<=4.3
  # - r-uwot
  - r-loom
  - r-svglite
  - bioconductor-scater
  - r-seuratdisk
  - r-remotes
  - bioconductor-multtest
  - r-metap
  - pandoc