name: test
dependencies:
  - bats
  - r-optparse
  - libpng
  - r-cairo
  - r-workflowscriptscommon
  - r-seurat=4.0.5
  - r-uwot <0.1.11
  - r-loom
  - bioconductor-scater
  - r-seuratdisk
  - r-remotes
